# Generated by Django 5.2.6 on 2025-09-30 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('E', 'Expense'), ('R', 'Revenue')], max_length=1)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('annotations', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('current_installment', models.IntegerField(blank=True, null=True)),
                ('total_installments', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.bank')),
            ],
        ),
    ]
