# Generated by Django 5.2.8 on 2025-11-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_salary',
            field=models.BooleanField(default=False),
        ),
    ]
